package gssapi;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : src/header/gssapi/gssapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("gssapi_krb5")
public class gss_OID_desc extends StructObject {
	public gss_OID_desc() {
		super();
	}
	public gss_OID_desc(Pointer pointer) {
		super(pointer);
	}
	/// C type : OM_uint32
	@Field(0) 
	public int length() {
		return this.io.getIntField(this, 0);
	}
	/// C type : OM_uint32
	@Field(0) 
	public gss_OID_desc length(int length) {
		this.io.setIntField(this, 0, length);
		return this;
	}
	/// C type : void*
	@Field(1) 
	public Pointer<? > elements() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : void*
	@Field(1) 
	public gss_OID_desc elements(Pointer<? > elements) {
		this.io.setPointerField(this, 1, elements);
		return this;
	}
}
