/*
 * This file is part of WinRM.
 *
 * WinRM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * WinRM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with WinRM.  If not, see <http://www.gnu.org/licenses/>.
 */
package gssapi;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : src/header/gssapi/gssapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("gssapi") 
public class gss_context_stream_sizes extends StructObject {
	public gss_context_stream_sizes() {
		super();
	}
	public gss_context_stream_sizes(Pointer pointer) {
		super(pointer);
	}
	/// < size of header
	@Ptr 
	@Field(0) 
	public long header() {
		return this.io.getSizeTField(this, 0);
	}
	/// < size of header
	@Ptr 
	@Field(0) 
	public gss_context_stream_sizes header(long header) {
		this.io.setSizeTField(this, 0, header);
		return this;
	}
	/// < size of trailer
	@Ptr 
	@Field(1) 
	public long trailer() {
		return this.io.getSizeTField(this, 1);
	}
	/// < size of trailer
	@Ptr 
	@Field(1) 
	public gss_context_stream_sizes trailer(long trailer) {
		this.io.setSizeTField(this, 1, trailer);
		return this;
	}
	/// < maximum message size
	@Ptr 
	@Field(2) 
	public long max_msg_size() {
		return this.io.getSizeTField(this, 2);
	}
	/// < maximum message size
	@Ptr 
	@Field(2) 
	public gss_context_stream_sizes max_msg_size(long max_msg_size) {
		this.io.setSizeTField(this, 2, max_msg_size);
		return this;
	}
	/// < extra GSS_IOV_BUFFER_TYPE_EMPTY buffer to pass
	@Ptr 
	@Field(3) 
	public long buffers() {
		return this.io.getSizeTField(this, 3);
	}
	/// < extra GSS_IOV_BUFFER_TYPE_EMPTY buffer to pass
	@Ptr 
	@Field(3) 
	public gss_context_stream_sizes buffers(long buffers) {
		this.io.setSizeTField(this, 3, buffers);
		return this;
	}
	/**
	 * < Specificed optimal size of messages, also<br>
	 * is the maximum padding size<br>
	 * (GSS_IOV_BUFFER_TYPE_PADDING)
	 */
	@Ptr 
	@Field(4) 
	public long blocksize() {
		return this.io.getSizeTField(this, 4);
	}
	/**
	 * < Specificed optimal size of messages, also<br>
	 * is the maximum padding size<br>
	 * (GSS_IOV_BUFFER_TYPE_PADDING)
	 */
	@Ptr 
	@Field(4) 
	public gss_context_stream_sizes blocksize(long blocksize) {
		this.io.setSizeTField(this, 4, blocksize);
		return this;
	}
}
