package gssapi;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : src/header/gssapi/gssapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("gssapi") 
public class gss_channel_bindings_struct extends StructObject {
	public gss_channel_bindings_struct() {
		super();
	}
	public gss_channel_bindings_struct(Pointer pointer) {
		super(pointer);
	}
	/// C type : OM_uint32
	@Field(0) 
	public int initiator_addrtype() {
		return this.io.getIntField(this, 0);
	}
	/// C type : OM_uint32
	@Field(0) 
	public gss_channel_bindings_struct initiator_addrtype(int initiator_addrtype) {
		this.io.setIntField(this, 0, initiator_addrtype);
		return this;
	}
	/// C type : gss_buffer_desc
	@Field(1) 
	public gss_buffer_desc initiator_address() {
		return this.io.getNativeObjectField(this, 1);
	}
	/// C type : OM_uint32
	@Field(2) 
	public int acceptor_addrtype() {
		return this.io.getIntField(this, 2);
	}
	/// C type : OM_uint32
	@Field(2) 
	public gss_channel_bindings_struct acceptor_addrtype(int acceptor_addrtype) {
		this.io.setIntField(this, 2, acceptor_addrtype);
		return this;
	}
	/// C type : gss_buffer_desc
	@Field(3) 
	public gss_buffer_desc acceptor_address() {
		return this.io.getNativeObjectField(this, 3);
	}
	/// C type : gss_buffer_desc
	@Field(4) 
	public gss_buffer_desc application_data() {
		return this.io.getNativeObjectField(this, 4);
	}
}
