package gssapi;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : src/header/gssapi/gssapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("gssapi_krb5")
public class gss_buffer_desc extends StructObject {
	public gss_buffer_desc() {
		super();
	}
	public gss_buffer_desc(Pointer pointer) {
		super(pointer);
	}
	@Ptr 
	@Field(0) 
	public long length() {
		return this.io.getSizeTField(this, 0);
	}
	@Ptr 
	@Field(0) 
	public gss_buffer_desc length(long length) {
		this.io.setSizeTField(this, 0, length);
		return this;
	}
	/// C type : void*
	@Field(1) 
	public Pointer<? > value() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : void*
	@Field(1) 
	public gss_buffer_desc value(Pointer<? > value) {
		this.io.setPointerField(this, 1, value);
		return this;
	}
}
